name: 'Build docker image'

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push app image
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./Dockerfile
          tags: 96digital/inhouse-order-frontend:latest
          build-args: |
            VITE_CDN_HOST=https://dev-inhouse-order.sgp1.cdn.digitaloceanspaces.com
            VITE_AUTH_URL=https://inhouse-order.darklong.duckdns.org/auth
            VITE_GRAPHQL_URL=https://inhouse-order.darklong.duckdns.org/graphql
            VITE_GRAPHQL_WS=https://inhouse-order.darklong.duckdns.org/graphql
            VITE_SENTRY_DNS=https://538f8f3cae25016b892fa4c3a74429a6@o4505980401156096.ingest.sentry.io/4505985229258752


