name: 'Test'
on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 'Install dependencies'
        run: pnpm install

      - name: 'Build'
        run: pnpm run build

      - name: 'Lint'
        run: pnpm run lint

      - name: 'Test'
        run: pnpm run test

#      - name: 'Report Coverage'
#        if: always()
#        uses: davelosert/vitest-coverage-report-action@v2
